repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        args: ['--ignore=E501,W503,E231,E503,E203,F401']

  - repo: https://github.com/timothycrosley/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args:
          [
            '--line-length=88',
            '--use-parentheses',
            '--trailing-comma',
            '--multi-line=3',
          ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies:
          - types-requests
          - pandas-stubs
