repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        exclude: tests

  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        args: ['--ignore=E501,W503,E231,E503,E203,F401']
        exclude: tests

  - repo: https://github.com/timothycrosley/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args:
          [
            '--line-length=88',
            '--use-parentheses',
            '--trailing-comma',
            '--multi-line=3',
          ]
        exclude: tests

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        exclude: tests
