[mypy]
files = tagreader
check_untyped_defs = True
disallow_any_generics = True
# disallow_untyped_calls = True
disallow_untyped_defs = True
ignore_missing_imports = True
# Temporary fix for https://github.com/python/mypy/issues/10709:
ignore_missing_imports_per_module = True
implicit_reexport = False
local_partial_types = True
# no_implicit_optional = True
strict_equality = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True
warn_unused_configs = True

[mypy-tagreader.clients]
ignore_errors = True

[mypy-tagreader.odbc_handlers]
ignore_errors = True

[mypy-tagreader.utils]
ignore_errors = True

[mypy-tagreader.web_handlers]
ignore_errors = True